# =============================================================================
# .latexmkrc -- one-click build of all submission PDFs for this CAS template
# =============================================================================
# Usage: configure your editor (TeXstudio / VS Code LaTeX Workshop / TeXworks
# etc.) to use latexmk as the build tool, open the main file
# cas-dc-template-main.tex and hit "Build" once. This file turns that single
# build into incremental compilations of all 5 submission PDFs:
#
#   cas-dc-template-main-full.pdf                full (text + GA + highlights)
#   cas-dc-template-main-without-abstract.pdf    text only (default writing build)
#   cas-dc-template-main-blind.pdf               double-blind text
#   cas-dc-template-main-graphical-abstract.pdf  graphical abstract only
#   cas-dc-template-main-highlights.pdf          highlights only
#
# The editable highlights Word file is produced separately by
# make_highlights_docx.ps1 (or by running compile_all.bat).
#
# How it works ("custom rules"): a version-entry file {base}-{ver}.tex is
# auto-generated for every variant in the version table below; each entry just
# passes its \def switch and \input's the main file. The command line is then
# rewritten so that whichever file the editor passes, the whole variant set is
# compiled. latexmk keeps everything incremental (only stale variants rebuild).
# =============================================================================

$pdf_mode = 1;                # pdflatex, output PDF directly
$bibtex_use = 1;              # run bibtex automatically when needed
$out_dir = '.';               # keep outputs in the project root (like compile_all.bat)
$preview_mode = 0;            # never auto-open a preview (editor shows the PDF itself)
$silence_logfile_warnings = 1;

# -----------------------------------------------------------------------------
# 1. Locate the main file: auto-detect *-main.tex (same rule as compile_all.bat)
# -----------------------------------------------------------------------------
my $MAIN;
my @candidates = glob('*-main.tex');
if (@candidates == 0) {
    die "latexmkrc: no *-main.tex main file found in the current directory.\n";
} elsif (@candidates > 1) {
    die "latexmkrc: multiple *-main.tex files found; keep only one: @candidates\n";
} else {
    $MAIN = $candidates[0];
}
(my $BASE = $MAIN) =~ s/\.tex$//;

# -----------------------------------------------------------------------------
# 2. Version table (the custom rule): variant name => \def switch for the main file
# -----------------------------------------------------------------------------
my @VERSIONS = (
    [ 'full',               '\def\FULL{1}' ],
    [ 'without-abstract',   '\def\WITHOUTABSTRACT{1}' ],
    [ 'blind',              '\def\BLIND{1}\def\WITHOUTABSTRACT{1}' ],
    [ 'graphical-abstract', '\def\GRAPHICALONLY{1}' ],
    [ 'highlights',         '\def\HIGHLIGHTSONLY{1}' ],
);

# Version entry files: {base}-{ver}.tex, e.g. cas-dc-template-main-full.tex
my @ENTRIES;
for my $v (@VERSIONS) {
    push @ENTRIES, "$BASE-$v->[0].tex";
}

# -----------------------------------------------------------------------------
# 3. Auto-generate the entry files (recreate only when missing)
# -----------------------------------------------------------------------------
sub ensure_entries {
    for my $i (0 .. $#VERSIONS) {
        my ($ver, $defs) = @{ $VERSIONS[$i] };
        my $entry = $ENTRIES[$i];
        if (!-e $entry) {
            my $content = "% Auto-generated by .latexmkrc -- do not edit.\n"
                        . "% !TEX program = pdflatex\n"
                        . "% !TEX root = $MAIN\n"
                        . "$defs\\input{$BASE}\n";
            open my $fh, '>', $entry or die "latexmkrc: cannot create $entry: $!";
            print $fh $content;
            close $fh;
            print "latexmkrc: generated version entry $entry\n";
        }
    }
}

ensure_entries();

# Compile every variant when no file is given on the command line
@default_files = @ENTRIES;

# -----------------------------------------------------------------------------
# 4. Rewrite the command line: when the editor passes the main file, replace it
#    with the whole set of version entries (one "Build" click => all PDFs).
#    Any other explicit file (e.g. a single sub-file) is left untouched.
#    The main file is matched with or without a directory prefix / .tex suffix.
# -----------------------------------------------------------------------------
my @new_args;
for my $arg (@ARGV) {
    (my $arg_base = $arg) =~ s{^.*[\\/]}{};   # strip any directory prefix
    $arg_base =~ s/\.tex$//;
    if ($arg_base eq $BASE) {
        push @new_args, @ENTRIES;
    } else {
        push @new_args, $arg;
    }
}
@ARGV = @new_args;
